FROM node:latest

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    git \
    nano \
    unzip \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxi6 \
    libxtst6 \
    libnss3 \
    libgtk-3-0 \
    libasound2 \
    libatk-bridge2.0-0 \
    libxss1 \
    libxkbfile1 \
    libgtk2.0-0 \
    libgconf-2-4 \
    libnotify-dev \
    xvfb \
 && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb && \
    dpkg -i chrome.deb || apt-get install -yf && \
    rm chrome.deb

RUN npm install -g live-server

# run bash
CMD ["/bin/bash"]